### ISSUE TITLE
snippet for postcode data download?

### ISSUE THREAD

**Issue by olivierthereaux** [theodi/synthetic-data-tutorial#1]
How about adding code snippet to make sure the postcodes data is downloaded and named appropriately?

`curl -o "London postcodes.csv" https://www.doogal.co.uk/UKPostcodesCSV.ashx?region=E12000007 
`
?

**Comment by olivierthereaux** [comment]
also not sure about having a space in file name. Not super foolproof.

**Comment by fionntan** [comment]
Ok, I've added a curl snippet in to it. 

Yeah I don't like the space either but that's how they named the file. Shouldn't cause any problems though.
